[package]
name = "xbase"
version = "0.1.0"
edition = "2021"

[features]
default     = [ ]
xcodegen    = [ "async", "dirs" ]
daemon      = [ "serial", "compilation", "logging", "async", "watcher", "proc", "xcodegen", "parity-tokio-ipc", "nvim-rs", "async-stream", "tokio-stream", "strum" ]
server      = [ "serial", "logging", "dirs", "bsp-server", "url", "wax", "shell-words", "compilation", "strum" ]
lua         = [ "mlua", "serial", "strum" ]
serial      = [ "serde", "serde_json", "serde_yaml" ]
compilation = [ "serial", "lazy_static", "shell-words", "xcode" ]
logging     = [ "tracing", "tracing-appender", "tracing-subscriber" ]
async       = [ "tokio", "async-trait" ]
proc        = [ "libproc" ]
watcher     = [ "dirs", "notify", "wax" ]
jsonrpc     = [ "serial" ]
xcode       = [ "xcodebuild" ]

[lib]
name = "xbase"
path = "src/lib.rs"

[workspace]
members = [
  "lua/xbase",
]

[[bin]]
name = "xbase-daemon"
path = "src/daemon/bin.rs"
required-features = ["daemon"]

[[bin]]
name = "xbase-server"
path = "src/server/bin.rs"
required-features = [ "server" ]

[dependencies]
# Error Handling
anyhow                = "^1.0.42"
# suffix-position pipeline
tap                   = "1.0.1"
# Serialization Feature
serde                 = { version = "1.0",    features = ["derive"], optional = true }
serde_json            = { version = "1.0.79", optional = true }
serde_yaml            = { version = "0.8.23", optional = true }
# Async Runtime Feature
tokio                 = { version = "1.17.0", features = ["full"], optional = true }
tokio-util            = { version = "0.7.1",  features = ["codec"], optional = true }
async-trait           = { version = "0.1.52", optional = true }
# Logging Feature
tracing               = { version = "0.1.32", optional = true }
tracing-subscriber    = { version = "0.3.9",  features = ["env-filter"], optional = true}
tracing-appender      = { version = "0.2.1",  optional = true }
# Filesystem watcher
notify                = { version = "5.0.0-pre.13", optional = true }
dirs                  = { version = "4.0",    optional = true }
wax                   = { version = "0.4.0",  optional = true }
# Build Logs/Command Compilation feature
lazy_static           = { version = "1.4.0",  optional = true }
shell-words           = { version  = "1.1.0", optional = true }
# Other
mlua                  = { version = "0.7.4",  features = ["lua51", "vendored"], optional = true } 
bsp-server            = { version  = "0.1.2", path = "../../rust/build-server-protocol/bsp-server/", optional = true }
xcodebuild            = { version  = "0.1.2", path = "../../rust/xcodebuild/", optional = true, features = ["tracing"] }
# Proc feature: processes, processors, disks, components and networks (sysinfo = "0.23.5")
libproc               = { version = "0.11.1", optional = true }
url                   = { version = "2.2.2",  features = ["serde"], optional = true }
nvim-rs               = { version = "0.4.0", optional = true, features = ["use_tokio"] }
parity-tokio-ipc      = { version = "0.9.0", optional = true }
strum                 = { version = "0.24.0",  features = ["derive"], optional  = true }
tokio-stream          = { version = "0.1.8", features = ["io-util"], optional = true  }
async-stream          = { version = "0.3.3", optional = true }
