name: daily
on:
  schedule:
    - cron: "* 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  jgehrcke:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: github-repo-stats
        uses: jgehrcke/github-repo-stats@v1.0.0
